# Generated by Django 2.2.5 on 2022-01-19 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculum',
            options={'managed': False, 'ordering': ['-id', 'name']},
        ),
    ]
