# Generated by Django 2.2.5 on 2022-01-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0002_auto_20220118_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Army_shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('type', models.TextField()),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'army_shop',
                'ordering': ['-id', 'year', 'month', 'type', 'name'],
                'managed': False,
            },
        ),
    ]
